// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: ourchat/read/v1/read.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "ourchat.read.v1";

/** 已读上报:socket 事件 read.report / REST POST /user/read。 */
export interface ReadReportInput {
  conversationId: string;
  /** JSON string */
  uptoSeq: number;
}

/** 已读同步:socket 下行 read.sync,多端一致推进。 */
export interface ReadSync {
  conversationId: string;
  uptoSeq: number;
}

function createBaseReadReportInput(): ReadReportInput {
  return { conversationId: "", uptoSeq: 0 };
}

export const ReadReportInput: MessageFns<ReadReportInput> = {
  encode(message: ReadReportInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== "") {
      writer.uint32(10).string(message.conversationId);
    }
    if (message.uptoSeq !== 0) {
      writer.uint32(16).int64(message.uptoSeq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadReportInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadReportInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.uptoSeq = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadReportInput {
    return {
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      uptoSeq: isSet(object.uptoSeq)
        ? globalThis.Number(object.uptoSeq)
        : isSet(object.upto_seq)
        ? globalThis.Number(object.upto_seq)
        : 0,
    };
  },

  toJSON(message: ReadReportInput): unknown {
    const obj: any = {};
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.uptoSeq !== 0) {
      obj.uptoSeq = Math.round(message.uptoSeq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadReportInput>, I>>(base?: I): ReadReportInput {
    return ReadReportInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadReportInput>, I>>(object: I): ReadReportInput {
    const message = createBaseReadReportInput();
    message.conversationId = object.conversationId ?? "";
    message.uptoSeq = object.uptoSeq ?? 0;
    return message;
  },
};

function createBaseReadSync(): ReadSync {
  return { conversationId: "", uptoSeq: 0 };
}

export const ReadSync: MessageFns<ReadSync> = {
  encode(message: ReadSync, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== "") {
      writer.uint32(10).string(message.conversationId);
    }
    if (message.uptoSeq !== 0) {
      writer.uint32(16).int64(message.uptoSeq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadSync {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadSync();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.uptoSeq = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadSync {
    return {
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      uptoSeq: isSet(object.uptoSeq)
        ? globalThis.Number(object.uptoSeq)
        : isSet(object.upto_seq)
        ? globalThis.Number(object.upto_seq)
        : 0,
    };
  },

  toJSON(message: ReadSync): unknown {
    const obj: any = {};
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.uptoSeq !== 0) {
      obj.uptoSeq = Math.round(message.uptoSeq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadSync>, I>>(base?: I): ReadSync {
    return ReadSync.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadSync>, I>>(object: I): ReadSync {
    const message = createBaseReadSync();
    message.conversationId = object.conversationId ?? "";
    message.uptoSeq = object.uptoSeq ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
