// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: ourchat/edge/v1/realtime.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "ourchat.edge.v1";

export interface EdgeFrame {
  /** gateway → server:业务上行帧(原样透传客户端信封) */
  uplink?:
    | UplinkFrame
    | undefined;
  /** server → gateway:message.ack / message.error 回投 */
  ack?:
    | UplinkAck
    | undefined;
  /** gateway → server:连接断开通知(替代 POST /internal/gateway/disconnect) */
  closed?:
    | ConnClosed
    | undefined;
  /** server → gateway:下行帧(目标态,替代 Redis gw:downlink) */
  downlink?: DownlinkFrame | undefined;
}

/** 业务上行帧。raw_frame 为客户端信封 {type,data} 的 JSON(message.send / read.report / call:* / heartbeat 除外)。 */
export interface UplinkFrame {
  /** 身份以网关 JWT 验签结果为准(与 X-User-Id 同义),不信任帧内自报 */
  userId: number;
  deviceId: string;
  /** 幂等键(重发复用;服务端 (conversation_id, sender_id, client_msg_id) 唯一约束兜底) */
  clientMsgId: string;
  /** 信封 JSON:{"type":"message.send","data":{...}} */
  rawFrame: Uint8Array;
}

/**
 * 上行确认:按 client_msg_id 关联回投给发送方连接。
 * ok=false 时必须带 error 与 client_msg_id(客户端据此收敛 pending,不再依赖超时重发)。
 */
export interface UplinkAck {
  clientMsgId: string;
  ok: boolean;
  seq: number;
  serverMsgId: number;
  error: string;
  /**
   * 回投给客户端的原始信封 JSON(对齐 HTTP 模式的响应体语义):
   *   message.send → {"type":"message.ack","data":{...}};call:* 信令响应同理;
   *   空 = 仅收敛 pending 不回投(read.report 等 204 语义)。
   */
  rawResponse: Uint8Array;
  /** 确认归属的用户(网关据此定位分片内的等待者;与上行帧同值)。 */
  userId: number;
}

/** 连接断开通知(fire-and-forget 语义,与 /internal/gateway/disconnect 等价)。 */
export interface ConnClosed {
  userId: number;
  deviceId: string;
}

/**
 * 下行帧:server 定向推给某用户在某网关副本上的连接。
 * target_device_id / except_device_id 语义与 gw:downlink 载荷一致(属主路由 / 排除本端)。
 */
export interface DownlinkFrame {
  userId: number;
  /** 非空:仅投指定设备(call:rejoin);与 except 互斥 */
  targetDeviceId: string;
  /** 非空:投除指定设备外的全部连接(read.sync);与 target 互斥 */
  exceptDeviceId: string;
  /** 客户端最终收到的 WS 帧信封 JSON */
  rawFrame: Uint8Array;
}

function createBaseEdgeFrame(): EdgeFrame {
  return { uplink: undefined, ack: undefined, closed: undefined, downlink: undefined };
}

export const EdgeFrame: MessageFns<EdgeFrame> = {
  encode(message: EdgeFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uplink !== undefined) {
      UplinkFrame.encode(message.uplink, writer.uint32(10).fork()).join();
    }
    if (message.ack !== undefined) {
      UplinkAck.encode(message.ack, writer.uint32(18).fork()).join();
    }
    if (message.closed !== undefined) {
      ConnClosed.encode(message.closed, writer.uint32(26).fork()).join();
    }
    if (message.downlink !== undefined) {
      DownlinkFrame.encode(message.downlink, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EdgeFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEdgeFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uplink = UplinkFrame.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ack = UplinkAck.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.closed = ConnClosed.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.downlink = DownlinkFrame.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EdgeFrame {
    return {
      uplink: isSet(object.uplink) ? UplinkFrame.fromJSON(object.uplink) : undefined,
      ack: isSet(object.ack) ? UplinkAck.fromJSON(object.ack) : undefined,
      closed: isSet(object.closed) ? ConnClosed.fromJSON(object.closed) : undefined,
      downlink: isSet(object.downlink) ? DownlinkFrame.fromJSON(object.downlink) : undefined,
    };
  },

  toJSON(message: EdgeFrame): unknown {
    const obj: any = {};
    if (message.uplink !== undefined) {
      obj.uplink = UplinkFrame.toJSON(message.uplink);
    }
    if (message.ack !== undefined) {
      obj.ack = UplinkAck.toJSON(message.ack);
    }
    if (message.closed !== undefined) {
      obj.closed = ConnClosed.toJSON(message.closed);
    }
    if (message.downlink !== undefined) {
      obj.downlink = DownlinkFrame.toJSON(message.downlink);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EdgeFrame>, I>>(base?: I): EdgeFrame {
    return EdgeFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EdgeFrame>, I>>(object: I): EdgeFrame {
    const message = createBaseEdgeFrame();
    message.uplink = (object.uplink !== undefined && object.uplink !== null)
      ? UplinkFrame.fromPartial(object.uplink)
      : undefined;
    message.ack = (object.ack !== undefined && object.ack !== null) ? UplinkAck.fromPartial(object.ack) : undefined;
    message.closed = (object.closed !== undefined && object.closed !== null)
      ? ConnClosed.fromPartial(object.closed)
      : undefined;
    message.downlink = (object.downlink !== undefined && object.downlink !== null)
      ? DownlinkFrame.fromPartial(object.downlink)
      : undefined;
    return message;
  },
};

function createBaseUplinkFrame(): UplinkFrame {
  return { userId: 0, deviceId: "", clientMsgId: "", rawFrame: new Uint8Array(0) };
}

export const UplinkFrame: MessageFns<UplinkFrame> = {
  encode(message: UplinkFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int64(message.userId);
    }
    if (message.deviceId !== "") {
      writer.uint32(18).string(message.deviceId);
    }
    if (message.clientMsgId !== "") {
      writer.uint32(26).string(message.clientMsgId);
    }
    if (message.rawFrame.length !== 0) {
      writer.uint32(34).bytes(message.rawFrame);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UplinkFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUplinkFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clientMsgId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.rawFrame = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UplinkFrame {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      deviceId: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
      clientMsgId: isSet(object.clientMsgId)
        ? globalThis.String(object.clientMsgId)
        : isSet(object.client_msg_id)
        ? globalThis.String(object.client_msg_id)
        : "",
      rawFrame: isSet(object.rawFrame)
        ? bytesFromBase64(object.rawFrame)
        : isSet(object.raw_frame)
        ? bytesFromBase64(object.raw_frame)
        : new Uint8Array(0),
    };
  },

  toJSON(message: UplinkFrame): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.clientMsgId !== "") {
      obj.clientMsgId = message.clientMsgId;
    }
    if (message.rawFrame.length !== 0) {
      obj.rawFrame = base64FromBytes(message.rawFrame);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UplinkFrame>, I>>(base?: I): UplinkFrame {
    return UplinkFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UplinkFrame>, I>>(object: I): UplinkFrame {
    const message = createBaseUplinkFrame();
    message.userId = object.userId ?? 0;
    message.deviceId = object.deviceId ?? "";
    message.clientMsgId = object.clientMsgId ?? "";
    message.rawFrame = object.rawFrame ?? new Uint8Array(0);
    return message;
  },
};

function createBaseUplinkAck(): UplinkAck {
  return { clientMsgId: "", ok: false, seq: 0, serverMsgId: 0, error: "", rawResponse: new Uint8Array(0), userId: 0 };
}

export const UplinkAck: MessageFns<UplinkAck> = {
  encode(message: UplinkAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMsgId !== "") {
      writer.uint32(10).string(message.clientMsgId);
    }
    if (message.ok !== false) {
      writer.uint32(16).bool(message.ok);
    }
    if (message.seq !== 0) {
      writer.uint32(24).int64(message.seq);
    }
    if (message.serverMsgId !== 0) {
      writer.uint32(32).int64(message.serverMsgId);
    }
    if (message.error !== "") {
      writer.uint32(42).string(message.error);
    }
    if (message.rawResponse.length !== 0) {
      writer.uint32(50).bytes(message.rawResponse);
    }
    if (message.userId !== 0) {
      writer.uint32(56).int64(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UplinkAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUplinkAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMsgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.seq = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.serverMsgId = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.rawResponse = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UplinkAck {
    return {
      clientMsgId: isSet(object.clientMsgId)
        ? globalThis.String(object.clientMsgId)
        : isSet(object.client_msg_id)
        ? globalThis.String(object.client_msg_id)
        : "",
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      serverMsgId: isSet(object.serverMsgId)
        ? globalThis.Number(object.serverMsgId)
        : isSet(object.server_msg_id)
        ? globalThis.Number(object.server_msg_id)
        : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      rawResponse: isSet(object.rawResponse)
        ? bytesFromBase64(object.rawResponse)
        : isSet(object.raw_response)
        ? bytesFromBase64(object.raw_response)
        : new Uint8Array(0),
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
    };
  },

  toJSON(message: UplinkAck): unknown {
    const obj: any = {};
    if (message.clientMsgId !== "") {
      obj.clientMsgId = message.clientMsgId;
    }
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.serverMsgId !== 0) {
      obj.serverMsgId = Math.round(message.serverMsgId);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.rawResponse.length !== 0) {
      obj.rawResponse = base64FromBytes(message.rawResponse);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UplinkAck>, I>>(base?: I): UplinkAck {
    return UplinkAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UplinkAck>, I>>(object: I): UplinkAck {
    const message = createBaseUplinkAck();
    message.clientMsgId = object.clientMsgId ?? "";
    message.ok = object.ok ?? false;
    message.seq = object.seq ?? 0;
    message.serverMsgId = object.serverMsgId ?? 0;
    message.error = object.error ?? "";
    message.rawResponse = object.rawResponse ?? new Uint8Array(0);
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseConnClosed(): ConnClosed {
  return { userId: 0, deviceId: "" };
}

export const ConnClosed: MessageFns<ConnClosed> = {
  encode(message: ConnClosed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int64(message.userId);
    }
    if (message.deviceId !== "") {
      writer.uint32(18).string(message.deviceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnClosed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnClosed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnClosed {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      deviceId: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
    };
  },

  toJSON(message: ConnClosed): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnClosed>, I>>(base?: I): ConnClosed {
    return ConnClosed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnClosed>, I>>(object: I): ConnClosed {
    const message = createBaseConnClosed();
    message.userId = object.userId ?? 0;
    message.deviceId = object.deviceId ?? "";
    return message;
  },
};

function createBaseDownlinkFrame(): DownlinkFrame {
  return { userId: 0, targetDeviceId: "", exceptDeviceId: "", rawFrame: new Uint8Array(0) };
}

export const DownlinkFrame: MessageFns<DownlinkFrame> = {
  encode(message: DownlinkFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int64(message.userId);
    }
    if (message.targetDeviceId !== "") {
      writer.uint32(18).string(message.targetDeviceId);
    }
    if (message.exceptDeviceId !== "") {
      writer.uint32(26).string(message.exceptDeviceId);
    }
    if (message.rawFrame.length !== 0) {
      writer.uint32(34).bytes(message.rawFrame);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DownlinkFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownlinkFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.targetDeviceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.exceptDeviceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.rawFrame = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownlinkFrame {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      targetDeviceId: isSet(object.targetDeviceId)
        ? globalThis.String(object.targetDeviceId)
        : isSet(object.target_device_id)
        ? globalThis.String(object.target_device_id)
        : "",
      exceptDeviceId: isSet(object.exceptDeviceId)
        ? globalThis.String(object.exceptDeviceId)
        : isSet(object.except_device_id)
        ? globalThis.String(object.except_device_id)
        : "",
      rawFrame: isSet(object.rawFrame)
        ? bytesFromBase64(object.rawFrame)
        : isSet(object.raw_frame)
        ? bytesFromBase64(object.raw_frame)
        : new Uint8Array(0),
    };
  },

  toJSON(message: DownlinkFrame): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.targetDeviceId !== "") {
      obj.targetDeviceId = message.targetDeviceId;
    }
    if (message.exceptDeviceId !== "") {
      obj.exceptDeviceId = message.exceptDeviceId;
    }
    if (message.rawFrame.length !== 0) {
      obj.rawFrame = base64FromBytes(message.rawFrame);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownlinkFrame>, I>>(base?: I): DownlinkFrame {
    return DownlinkFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownlinkFrame>, I>>(object: I): DownlinkFrame {
    const message = createBaseDownlinkFrame();
    message.userId = object.userId ?? 0;
    message.targetDeviceId = object.targetDeviceId ?? "";
    message.exceptDeviceId = object.exceptDeviceId ?? "";
    message.rawFrame = object.rawFrame ?? new Uint8Array(0);
    return message;
  },
};

export type RealtimeService = typeof RealtimeService;
export const RealtimeService = {
  /**
   * 双向流:gateway 为每条流建立连接并按 userId 哈希分片(同用户帧恒落同一流,
   * ack/断连与上行帧同流返回,无需跨流关联)。目标态下行帧亦经此流(过渡期保留 Redis gw:downlink)。
   */
  stream: {
    path: "/ourchat.edge.v1.Realtime/Stream" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: EdgeFrame): Buffer => Buffer.from(EdgeFrame.encode(value).finish()),
    requestDeserialize: (value: Buffer): EdgeFrame => EdgeFrame.decode(value),
    responseSerialize: (value: EdgeFrame): Buffer => Buffer.from(EdgeFrame.encode(value).finish()),
    responseDeserialize: (value: Buffer): EdgeFrame => EdgeFrame.decode(value),
  },
} as const;

export interface RealtimeServer extends UntypedServiceImplementation {
  /**
   * 双向流:gateway 为每条流建立连接并按 userId 哈希分片(同用户帧恒落同一流,
   * ack/断连与上行帧同流返回,无需跨流关联)。目标态下行帧亦经此流(过渡期保留 Redis gw:downlink)。
   */
  stream: handleBidiStreamingCall<EdgeFrame, EdgeFrame>;
}

export interface RealtimeClient extends Client {
  /**
   * 双向流:gateway 为每条流建立连接并按 userId 哈希分片(同用户帧恒落同一流,
   * ack/断连与上行帧同流返回,无需跨流关联)。目标态下行帧亦经此流(过渡期保留 Redis gw:downlink)。
   */
  stream(): ClientDuplexStream<EdgeFrame, EdgeFrame>;
  stream(options: Partial<CallOptions>): ClientDuplexStream<EdgeFrame, EdgeFrame>;
  stream(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<EdgeFrame, EdgeFrame>;
}

export const RealtimeClient = makeGenericClientConstructor(RealtimeService, "ourchat.edge.v1.Realtime") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RealtimeClient;
  service: typeof RealtimeService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
