// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: ourchat/message/v1/message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../../../google/protobuf/struct.js";

export const protobufPackage = "ourchat.message.v1";

/**
 * REST 实体(Message/User/Conversation/Friend)已迁至 OpenAPI 单一契约(openapi/openapi.yaml);
 * 本文件仅保留 OpenAPI 描述不了的实时 WS 事件类型。FileInfo 被 SendMessageInput 复用,故保留于此。
 */
export interface FileInfo {
  fileName: string;
  /** 字节;int64 在 JSON 中为 string */
  fileSize: number;
  fileUrl: string;
  fileType: string;
  fileMd5: string;
}

/**
 * 上行发消息入参(socket 事件 message.send)。
 * sender_id 仅供前端回显参考,服务端以握手验签的 socket.userId 为准。
 */
export interface SendMessageInput {
  clientMsgId: string;
  conversationId: string;
  senderId?: number | undefined;
  content: string;
  type: string;
  mentions: number[];
  extra?: { [key: string]: any } | undefined;
  fileInfo?: FileInfo | undefined;
}

/** message.send 的 ack 回执。 */
export interface SendMessageAck {
  clientMsgId: string;
  seq: number;
  serverMsgId: number;
}

function createBaseFileInfo(): FileInfo {
  return { fileName: "", fileSize: 0, fileUrl: "", fileType: "", fileMd5: "" };
}

export const FileInfo: MessageFns<FileInfo> = {
  encode(message: FileInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileName !== "") {
      writer.uint32(10).string(message.fileName);
    }
    if (message.fileSize !== 0) {
      writer.uint32(16).int64(message.fileSize);
    }
    if (message.fileUrl !== "") {
      writer.uint32(26).string(message.fileUrl);
    }
    if (message.fileType !== "") {
      writer.uint32(34).string(message.fileType);
    }
    if (message.fileMd5 !== "") {
      writer.uint32(42).string(message.fileMd5);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.fileSize = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fileUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.fileType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fileMd5 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileInfo {
    return {
      fileName: isSet(object.fileName)
        ? globalThis.String(object.fileName)
        : isSet(object.file_name)
        ? globalThis.String(object.file_name)
        : "",
      fileSize: isSet(object.fileSize)
        ? globalThis.Number(object.fileSize)
        : isSet(object.file_size)
        ? globalThis.Number(object.file_size)
        : 0,
      fileUrl: isSet(object.fileUrl)
        ? globalThis.String(object.fileUrl)
        : isSet(object.file_url)
        ? globalThis.String(object.file_url)
        : "",
      fileType: isSet(object.fileType)
        ? globalThis.String(object.fileType)
        : isSet(object.file_type)
        ? globalThis.String(object.file_type)
        : "",
      fileMd5: isSet(object.fileMd5)
        ? globalThis.String(object.fileMd5)
        : isSet(object.file_md5)
        ? globalThis.String(object.file_md5)
        : "",
    };
  },

  toJSON(message: FileInfo): unknown {
    const obj: any = {};
    if (message.fileName !== "") {
      obj.fileName = message.fileName;
    }
    if (message.fileSize !== 0) {
      obj.fileSize = Math.round(message.fileSize);
    }
    if (message.fileUrl !== "") {
      obj.fileUrl = message.fileUrl;
    }
    if (message.fileType !== "") {
      obj.fileType = message.fileType;
    }
    if (message.fileMd5 !== "") {
      obj.fileMd5 = message.fileMd5;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileInfo>, I>>(base?: I): FileInfo {
    return FileInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileInfo>, I>>(object: I): FileInfo {
    const message = createBaseFileInfo();
    message.fileName = object.fileName ?? "";
    message.fileSize = object.fileSize ?? 0;
    message.fileUrl = object.fileUrl ?? "";
    message.fileType = object.fileType ?? "";
    message.fileMd5 = object.fileMd5 ?? "";
    return message;
  },
};

function createBaseSendMessageInput(): SendMessageInput {
  return {
    clientMsgId: "",
    conversationId: "",
    senderId: undefined,
    content: "",
    type: "",
    mentions: [],
    extra: undefined,
    fileInfo: undefined,
  };
}

export const SendMessageInput: MessageFns<SendMessageInput> = {
  encode(message: SendMessageInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMsgId !== "") {
      writer.uint32(10).string(message.clientMsgId);
    }
    if (message.conversationId !== "") {
      writer.uint32(18).string(message.conversationId);
    }
    if (message.senderId !== undefined) {
      writer.uint32(24).int64(message.senderId);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    if (message.type !== "") {
      writer.uint32(42).string(message.type);
    }
    writer.uint32(50).fork();
    for (const v of message.mentions) {
      writer.int64(v);
    }
    writer.join();
    if (message.extra !== undefined) {
      Struct.encode(Struct.wrap(message.extra), writer.uint32(58).fork()).join();
    }
    if (message.fileInfo !== undefined) {
      FileInfo.encode(message.fileInfo, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMsgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.senderId = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.mentions.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.mentions.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.extra = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.fileInfo = FileInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessageInput {
    return {
      clientMsgId: isSet(object.clientMsgId)
        ? globalThis.String(object.clientMsgId)
        : isSet(object.client_msg_id)
        ? globalThis.String(object.client_msg_id)
        : "",
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      senderId: isSet(object.senderId)
        ? globalThis.Number(object.senderId)
        : isSet(object.sender_id)
        ? globalThis.Number(object.sender_id)
        : undefined,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      mentions: globalThis.Array.isArray(object?.mentions) ? object.mentions.map((e: any) => globalThis.Number(e)) : [],
      extra: isObject(object.extra) ? object.extra : undefined,
      fileInfo: isSet(object.fileInfo)
        ? FileInfo.fromJSON(object.fileInfo)
        : isSet(object.file_info)
        ? FileInfo.fromJSON(object.file_info)
        : undefined,
    };
  },

  toJSON(message: SendMessageInput): unknown {
    const obj: any = {};
    if (message.clientMsgId !== "") {
      obj.clientMsgId = message.clientMsgId;
    }
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.senderId !== undefined) {
      obj.senderId = Math.round(message.senderId);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.mentions?.length) {
      obj.mentions = message.mentions.map((e) => Math.round(e));
    }
    if (message.extra !== undefined) {
      obj.extra = message.extra;
    }
    if (message.fileInfo !== undefined) {
      obj.fileInfo = FileInfo.toJSON(message.fileInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessageInput>, I>>(base?: I): SendMessageInput {
    return SendMessageInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessageInput>, I>>(object: I): SendMessageInput {
    const message = createBaseSendMessageInput();
    message.clientMsgId = object.clientMsgId ?? "";
    message.conversationId = object.conversationId ?? "";
    message.senderId = object.senderId ?? undefined;
    message.content = object.content ?? "";
    message.type = object.type ?? "";
    message.mentions = object.mentions?.map((e) => e) || [];
    message.extra = object.extra ?? undefined;
    message.fileInfo = (object.fileInfo !== undefined && object.fileInfo !== null)
      ? FileInfo.fromPartial(object.fileInfo)
      : undefined;
    return message;
  },
};

function createBaseSendMessageAck(): SendMessageAck {
  return { clientMsgId: "", seq: 0, serverMsgId: 0 };
}

export const SendMessageAck: MessageFns<SendMessageAck> = {
  encode(message: SendMessageAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMsgId !== "") {
      writer.uint32(10).string(message.clientMsgId);
    }
    if (message.seq !== 0) {
      writer.uint32(16).int64(message.seq);
    }
    if (message.serverMsgId !== 0) {
      writer.uint32(24).int64(message.serverMsgId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMsgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.seq = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.serverMsgId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessageAck {
    return {
      clientMsgId: isSet(object.clientMsgId)
        ? globalThis.String(object.clientMsgId)
        : isSet(object.client_msg_id)
        ? globalThis.String(object.client_msg_id)
        : "",
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      serverMsgId: isSet(object.serverMsgId)
        ? globalThis.Number(object.serverMsgId)
        : isSet(object.server_msg_id)
        ? globalThis.Number(object.server_msg_id)
        : 0,
    };
  },

  toJSON(message: SendMessageAck): unknown {
    const obj: any = {};
    if (message.clientMsgId !== "") {
      obj.clientMsgId = message.clientMsgId;
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.serverMsgId !== 0) {
      obj.serverMsgId = Math.round(message.serverMsgId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessageAck>, I>>(base?: I): SendMessageAck {
    return SendMessageAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessageAck>, I>>(object: I): SendMessageAck {
    const message = createBaseSendMessageAck();
    message.clientMsgId = object.clientMsgId ?? "";
    message.seq = object.seq ?? 0;
    message.serverMsgId = object.serverMsgId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
