// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: ourchat/call/v1/call.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "ourchat.call.v1";

/** 通话参与者精简信息。 */
export interface CallUser {
  id: number;
  username: string;
  nickname: string;
  avatar: string;
}

/** WebRTC 会话描述(RTCSessionDescriptionInit)。 */
export interface SessionDescription {
  /** offer | answer */
  type: string;
  sdp: string;
}

/** WebRTC ICE 候选。 */
export interface IceCandidate {
  candidate: string;
  sdpMlineIndex?: number | undefined;
  sdpMid?: string | undefined;
}

/** call:start 发起通话。 */
export interface CallStart {
  /** call_{fromId}_{toId}_{timestamp} */
  callId: string;
  from?: CallUser | undefined;
  to?: CallUser | undefined;
  offer?:
    | SessionDescription
    | undefined;
  /** voice | video,视频复用同一套信令 */
  callType: string;
}

/** call:accept 接听。from/to 为 user id(现状如此,与 call:start 的对象形态不同)。 */
export interface CallAccept {
  callId: string;
  from: number;
  to: number;
  answer?: SessionDescription | undefined;
}

/** call:reject 拒接。 */
export interface CallReject {
  callId: string;
}

/** call:end 挂断。 */
export interface CallEnd {
  callId: string;
}

/** call:ice ICE 候选交换。 */
export interface CallIce {
  callId: string;
  candidate?: IceCandidate | undefined;
}

/** call:rejoin 刷新/断连后重新入会:重连方新建 PeerConnection,携新 offer 请求对端重协商。 */
export interface CallRejoin {
  callId: string;
  from?: CallUser | undefined;
  to?: CallUser | undefined;
  offer?: SessionDescription | undefined;
}

/** call:busy 服务端→主叫:被叫已在另一通通话中(忙线),不振铃。 */
export interface CallBusy {
  callId: string;
}

/** call:handled 服务端→被叫的其它设备/标签页:该通话已在别处被处理,停止振铃。 */
export interface CallHandled {
  callId: string;
  /** accepted | rejected | ended */
  status: string;
}

/** call:peer-reconnecting 服务端→对端:通话对方设备掉线,处于 grace 重连窗内。 */
export interface CallPeerReconnecting {
  callId: string;
}

function createBaseCallUser(): CallUser {
  return { id: 0, username: "", nickname: "", avatar: "" };
}

export const CallUser: MessageFns<CallUser> = {
  encode(message: CallUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.avatar !== "") {
      writer.uint32(34).string(message.avatar);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallUser {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
    };
  },

  toJSON(message: CallUser): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallUser>, I>>(base?: I): CallUser {
    return CallUser.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallUser>, I>>(object: I): CallUser {
    const message = createBaseCallUser();
    message.id = object.id ?? 0;
    message.username = object.username ?? "";
    message.nickname = object.nickname ?? "";
    message.avatar = object.avatar ?? "";
    return message;
  },
};

function createBaseSessionDescription(): SessionDescription {
  return { type: "", sdp: "" };
}

export const SessionDescription: MessageFns<SessionDescription> = {
  encode(message: SessionDescription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.sdp !== "") {
      writer.uint32(18).string(message.sdp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionDescription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionDescription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sdp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionDescription {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      sdp: isSet(object.sdp) ? globalThis.String(object.sdp) : "",
    };
  },

  toJSON(message: SessionDescription): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.sdp !== "") {
      obj.sdp = message.sdp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionDescription>, I>>(base?: I): SessionDescription {
    return SessionDescription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionDescription>, I>>(object: I): SessionDescription {
    const message = createBaseSessionDescription();
    message.type = object.type ?? "";
    message.sdp = object.sdp ?? "";
    return message;
  },
};

function createBaseIceCandidate(): IceCandidate {
  return { candidate: "", sdpMlineIndex: undefined, sdpMid: undefined };
}

export const IceCandidate: MessageFns<IceCandidate> = {
  encode(message: IceCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candidate !== "") {
      writer.uint32(10).string(message.candidate);
    }
    if (message.sdpMlineIndex !== undefined) {
      writer.uint32(16).int32(message.sdpMlineIndex);
    }
    if (message.sdpMid !== undefined) {
      writer.uint32(26).string(message.sdpMid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IceCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIceCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sdpMlineIndex = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdpMid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IceCandidate {
    return {
      candidate: isSet(object.candidate) ? globalThis.String(object.candidate) : "",
      sdpMlineIndex: isSet(object.sdpMlineIndex)
        ? globalThis.Number(object.sdpMlineIndex)
        : isSet(object.sdp_mline_index)
        ? globalThis.Number(object.sdp_mline_index)
        : undefined,
      sdpMid: isSet(object.sdpMid)
        ? globalThis.String(object.sdpMid)
        : isSet(object.sdp_mid)
        ? globalThis.String(object.sdp_mid)
        : undefined,
    };
  },

  toJSON(message: IceCandidate): unknown {
    const obj: any = {};
    if (message.candidate !== "") {
      obj.candidate = message.candidate;
    }
    if (message.sdpMlineIndex !== undefined) {
      obj.sdpMlineIndex = Math.round(message.sdpMlineIndex);
    }
    if (message.sdpMid !== undefined) {
      obj.sdpMid = message.sdpMid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IceCandidate>, I>>(base?: I): IceCandidate {
    return IceCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IceCandidate>, I>>(object: I): IceCandidate {
    const message = createBaseIceCandidate();
    message.candidate = object.candidate ?? "";
    message.sdpMlineIndex = object.sdpMlineIndex ?? undefined;
    message.sdpMid = object.sdpMid ?? undefined;
    return message;
  },
};

function createBaseCallStart(): CallStart {
  return { callId: "", from: undefined, to: undefined, offer: undefined, callType: "" };
}

export const CallStart: MessageFns<CallStart> = {
  encode(message: CallStart, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.from !== undefined) {
      CallUser.encode(message.from, writer.uint32(18).fork()).join();
    }
    if (message.to !== undefined) {
      CallUser.encode(message.to, writer.uint32(26).fork()).join();
    }
    if (message.offer !== undefined) {
      SessionDescription.encode(message.offer, writer.uint32(34).fork()).join();
    }
    if (message.callType !== "") {
      writer.uint32(42).string(message.callType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallStart {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallStart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = CallUser.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = CallUser.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.offer = SessionDescription.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.callType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallStart {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      from: isSet(object.from) ? CallUser.fromJSON(object.from) : undefined,
      to: isSet(object.to) ? CallUser.fromJSON(object.to) : undefined,
      offer: isSet(object.offer) ? SessionDescription.fromJSON(object.offer) : undefined,
      callType: isSet(object.callType)
        ? globalThis.String(object.callType)
        : isSet(object.call_type)
        ? globalThis.String(object.call_type)
        : "",
    };
  },

  toJSON(message: CallStart): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.from !== undefined) {
      obj.from = CallUser.toJSON(message.from);
    }
    if (message.to !== undefined) {
      obj.to = CallUser.toJSON(message.to);
    }
    if (message.offer !== undefined) {
      obj.offer = SessionDescription.toJSON(message.offer);
    }
    if (message.callType !== "") {
      obj.callType = message.callType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallStart>, I>>(base?: I): CallStart {
    return CallStart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallStart>, I>>(object: I): CallStart {
    const message = createBaseCallStart();
    message.callId = object.callId ?? "";
    message.from = (object.from !== undefined && object.from !== null) ? CallUser.fromPartial(object.from) : undefined;
    message.to = (object.to !== undefined && object.to !== null) ? CallUser.fromPartial(object.to) : undefined;
    message.offer = (object.offer !== undefined && object.offer !== null)
      ? SessionDescription.fromPartial(object.offer)
      : undefined;
    message.callType = object.callType ?? "";
    return message;
  },
};

function createBaseCallAccept(): CallAccept {
  return { callId: "", from: 0, to: 0, answer: undefined };
}

export const CallAccept: MessageFns<CallAccept> = {
  encode(message: CallAccept, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.from !== 0) {
      writer.uint32(16).int64(message.from);
    }
    if (message.to !== 0) {
      writer.uint32(24).int64(message.to);
    }
    if (message.answer !== undefined) {
      SessionDescription.encode(message.answer, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallAccept {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallAccept();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.from = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.to = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.answer = SessionDescription.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallAccept {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      from: isSet(object.from) ? globalThis.Number(object.from) : 0,
      to: isSet(object.to) ? globalThis.Number(object.to) : 0,
      answer: isSet(object.answer) ? SessionDescription.fromJSON(object.answer) : undefined,
    };
  },

  toJSON(message: CallAccept): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.from !== 0) {
      obj.from = Math.round(message.from);
    }
    if (message.to !== 0) {
      obj.to = Math.round(message.to);
    }
    if (message.answer !== undefined) {
      obj.answer = SessionDescription.toJSON(message.answer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallAccept>, I>>(base?: I): CallAccept {
    return CallAccept.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallAccept>, I>>(object: I): CallAccept {
    const message = createBaseCallAccept();
    message.callId = object.callId ?? "";
    message.from = object.from ?? 0;
    message.to = object.to ?? 0;
    message.answer = (object.answer !== undefined && object.answer !== null)
      ? SessionDescription.fromPartial(object.answer)
      : undefined;
    return message;
  },
};

function createBaseCallReject(): CallReject {
  return { callId: "" };
}

export const CallReject: MessageFns<CallReject> = {
  encode(message: CallReject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallReject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallReject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallReject {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
    };
  },

  toJSON(message: CallReject): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallReject>, I>>(base?: I): CallReject {
    return CallReject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallReject>, I>>(object: I): CallReject {
    const message = createBaseCallReject();
    message.callId = object.callId ?? "";
    return message;
  },
};

function createBaseCallEnd(): CallEnd {
  return { callId: "" };
}

export const CallEnd: MessageFns<CallEnd> = {
  encode(message: CallEnd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallEnd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallEnd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallEnd {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
    };
  },

  toJSON(message: CallEnd): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallEnd>, I>>(base?: I): CallEnd {
    return CallEnd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallEnd>, I>>(object: I): CallEnd {
    const message = createBaseCallEnd();
    message.callId = object.callId ?? "";
    return message;
  },
};

function createBaseCallIce(): CallIce {
  return { callId: "", candidate: undefined };
}

export const CallIce: MessageFns<CallIce> = {
  encode(message: CallIce, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.candidate !== undefined) {
      IceCandidate.encode(message.candidate, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallIce {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallIce();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallIce {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      candidate: isSet(object.candidate) ? IceCandidate.fromJSON(object.candidate) : undefined,
    };
  },

  toJSON(message: CallIce): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.candidate !== undefined) {
      obj.candidate = IceCandidate.toJSON(message.candidate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallIce>, I>>(base?: I): CallIce {
    return CallIce.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallIce>, I>>(object: I): CallIce {
    const message = createBaseCallIce();
    message.callId = object.callId ?? "";
    message.candidate = (object.candidate !== undefined && object.candidate !== null)
      ? IceCandidate.fromPartial(object.candidate)
      : undefined;
    return message;
  },
};

function createBaseCallRejoin(): CallRejoin {
  return { callId: "", from: undefined, to: undefined, offer: undefined };
}

export const CallRejoin: MessageFns<CallRejoin> = {
  encode(message: CallRejoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.from !== undefined) {
      CallUser.encode(message.from, writer.uint32(18).fork()).join();
    }
    if (message.to !== undefined) {
      CallUser.encode(message.to, writer.uint32(26).fork()).join();
    }
    if (message.offer !== undefined) {
      SessionDescription.encode(message.offer, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallRejoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallRejoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = CallUser.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = CallUser.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.offer = SessionDescription.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallRejoin {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      from: isSet(object.from) ? CallUser.fromJSON(object.from) : undefined,
      to: isSet(object.to) ? CallUser.fromJSON(object.to) : undefined,
      offer: isSet(object.offer) ? SessionDescription.fromJSON(object.offer) : undefined,
    };
  },

  toJSON(message: CallRejoin): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.from !== undefined) {
      obj.from = CallUser.toJSON(message.from);
    }
    if (message.to !== undefined) {
      obj.to = CallUser.toJSON(message.to);
    }
    if (message.offer !== undefined) {
      obj.offer = SessionDescription.toJSON(message.offer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallRejoin>, I>>(base?: I): CallRejoin {
    return CallRejoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallRejoin>, I>>(object: I): CallRejoin {
    const message = createBaseCallRejoin();
    message.callId = object.callId ?? "";
    message.from = (object.from !== undefined && object.from !== null) ? CallUser.fromPartial(object.from) : undefined;
    message.to = (object.to !== undefined && object.to !== null) ? CallUser.fromPartial(object.to) : undefined;
    message.offer = (object.offer !== undefined && object.offer !== null)
      ? SessionDescription.fromPartial(object.offer)
      : undefined;
    return message;
  },
};

function createBaseCallBusy(): CallBusy {
  return { callId: "" };
}

export const CallBusy: MessageFns<CallBusy> = {
  encode(message: CallBusy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallBusy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallBusy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallBusy {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
    };
  },

  toJSON(message: CallBusy): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallBusy>, I>>(base?: I): CallBusy {
    return CallBusy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallBusy>, I>>(object: I): CallBusy {
    const message = createBaseCallBusy();
    message.callId = object.callId ?? "";
    return message;
  },
};

function createBaseCallHandled(): CallHandled {
  return { callId: "", status: "" };
}

export const CallHandled: MessageFns<CallHandled> = {
  encode(message: CallHandled, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallHandled {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallHandled();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallHandled {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: CallHandled): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallHandled>, I>>(base?: I): CallHandled {
    return CallHandled.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallHandled>, I>>(object: I): CallHandled {
    const message = createBaseCallHandled();
    message.callId = object.callId ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseCallPeerReconnecting(): CallPeerReconnecting {
  return { callId: "" };
}

export const CallPeerReconnecting: MessageFns<CallPeerReconnecting> = {
  encode(message: CallPeerReconnecting, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallPeerReconnecting {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallPeerReconnecting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallPeerReconnecting {
    return {
      callId: isSet(object.callId)
        ? globalThis.String(object.callId)
        : isSet(object.call_id)
        ? globalThis.String(object.call_id)
        : "",
    };
  },

  toJSON(message: CallPeerReconnecting): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallPeerReconnecting>, I>>(base?: I): CallPeerReconnecting {
    return CallPeerReconnecting.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallPeerReconnecting>, I>>(object: I): CallPeerReconnecting {
    const message = createBaseCallPeerReconnecting();
    message.callId = object.callId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
